[build-system]
requires = ["setuptools>=60.0","wheel"]

build-backend = "setuptools.build_meta"

[project]
name = "expense_tracker"
version = "0.1.0"
dependencies = []

[project.scripts]
guezz_number = "expense_tracker.main:main"